name: mediq
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.4.4=py312h06a4308_0
  - aiohttp=3.10.5=py312h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py312h06a4308_0
  - anyio=4.6.2=py312h06a4308_0
  - attrs=24.2.0=py312h06a4308_0
  - aws-c-auth=0.7.22=h96bc93b_2
  - aws-c-cal=0.6.14=h88a6e22_1
  - aws-c-common=0.9.19=h4ab18f5_0
  - aws-c-compression=0.2.18=h83b837d_6
  - aws-c-event-stream=0.4.2=ha47c788_12
  - aws-c-http=0.8.1=h29d6fba_17
  - aws-c-io=0.14.8=h21d4f22_5
  - aws-c-mqtt=0.10.4=h759edc4_4
  - aws-c-s3=0.5.9=h594631b_3
  - aws-c-sdkutils=0.1.16=h83b837d_2
  - aws-checksums=0.1.18=h83b837d_6
  - aws-crt-cpp=0.26.9=he3a8b3b_0
  - aws-sdk-cpp=1.11.329=hba8bd5f_3
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.12.14=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - datasets=3.2.0=pyhd8ed1ab_0
  - dill=0.3.8=py312h06a4308_0
  - distro=1.9.0=py312h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.5.0=py312h5eee18b_0
  - fsspec=2024.6.1=py312h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - h11=0.14.0=py312h06a4308_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - huggingface_hub=0.24.6=py312h06a4308_0
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_1
  - jiter=0.6.1=py312hb02cf49_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarrow=16.1.0=hcb6531f_6_cpu
  - libarrow-acero=16.1.0=hac33072_6_cpu
  - libarrow-dataset=16.1.0=hac33072_6_cpu
  - libarrow-substrait=16.1.0=h7e0c224_6_cpu
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcrc32c=1.1.2=h6a678d5_0
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libgoogle-cloud=2.24.0=h2736e30_0
  - libgoogle-cloud-storage=2.24.0=h3d9a0c8_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libparquet=16.1.0=h6a7eafb_6_cpu
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpmath=1.3.0=py312h06a4308_0
  - multidict=6.1.0=py312h5eee18b_0
  - multiprocess=0.70.15=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py312h06a4308_0
  - numexpr=2.10.1=py312h3c60e43_0
  - numpy=2.0.1=py312hc5e2394_1
  - numpy-base=2.0.1=py312h0da6c21_1
  - openai=1.57.4=pyhd8ed1ab_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.4.0=hb9d3cd8_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.2=py312h06a4308_0
  - pandas=2.2.3=py312h6a678d5_0
  - pillow=11.0.0=py312hcea889d_1
  - pip=24.2=py312h06a4308_0
  - propcache=0.2.0=py312h5eee18b_0
  - pyarrow=16.1.0=py312h9cebb41_2
  - pyarrow-core=16.1.0=py312h0983c49_2_cpu
  - pydantic=2.8.2=py312h06a4308_0
  - pydantic-core=2.20.1=py312hb02cf49_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py312h5eee18b_1
  - python_abi=3.12=5_cp312
  - pytorch=2.5.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h5eee18b_0
  - regex=2024.9.11=py312h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - s2n=1.4.15=he19d79f_0
  - safetensors=0.4.5=py312hc50d6dc_1
  - setuptools=75.1.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.21.0=py312h8360d73_0
  - torchaudio=2.5.1=py312_cu124
  - torchtriton=3.1.0=py312
  - torchvision=0.20.1=py312_cu124
  - tqdm=4.66.5=py312he106c6f_0
  - transformers=4.47.1=pyhd8ed1ab_0
  - typing-extensions=4.11.0=py312h06a4308_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - urllib3=2.2.3=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py312h5eee18b_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
